/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BInputGroupAppend: typeof import('bootstrap-vue-next')['BInputGroupAppend']
    BInputGroupPrepend: typeof import('bootstrap-vue-next')['BInputGroupPrepend']
    BInputGroupText: typeof import('bootstrap-vue-next')['BInputGroupText']
    FormResults: typeof import('./src/components/FormResults.vue')['default']
    HomeTitle: typeof import('./src/components/HomeTitle.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/SearchForm.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
